### ISSUE TITLE
Hero required is obyn, but was not found

### ISSUE THREAD

**Issue by FishLaSlip** [TheJsp/BloonsTD6Bot#6]
If you are still on this, I have obyn equipped, but I keep getting the error

`ValueError: Incorrect hero expected. Hero required is obyn, but was not found`

![Annotation 2020-07-21 064248](https://user-images.githubusercontent.com/68549677/88017361-6bb90880-cb1d-11ea-9d53-5e4fab39ca95.jpg)

I also thought that the new menu introduced in 18.0 when you beat a game would break this a bit when you finish

![image](https://user-images.githubusercontent.com/68549677/88017658-04e81f00-cb1e-11ea-9ae1-b9b23f76ac4f.png)

**Comment by ConciseFishy** [comment]
Fixed by running the game in 1920×1080 full screen

**Comment by JSpeleers** [comment]
Hi @FishLaSlip , apologies for the late response, but was,'t expecting any real interests. I found that after each BTD6 update, the images would somehow be outdated and the bot would not be able to find them on screen. So to fix this, one should take new snippets of the buttons (heroes, maps, skills etc) and store them under `./resources/`. As I'm not actively playing this game anymore, I'm not actively updating these. I will mark this in the README.
